vich_uploader:
    db_driver: orm
    metadata:
        type: attrribute

    mappings:
       vehicule_images:
           uri_prefix: /images/vehicule_images
           upload_destination: '%kernel.project_dir%/public/images/vehicule'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
